[tool.poetry]
name = "ace_ai"
version = "0.1.0"
description = ""
authors = ["Ace Fan <hongfan.s.f@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.11"
pandas = "^2.3.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
